In [1]:
!source ../.venv/bin/activate

import pandas as pd
from lmfocus.utils import (
    RANDOM_FOCUS_MARKERS,
    GEMMA_MODELS,
    QWEN_3_MODELS,
    QWEN_35_MODELS,
)
from itertools import product

stats_folder = "../stats/"

In [2]:
df_1 = pd.read_csv(stats_folder + 'stats_exp_01.csv')
df_2 = pd.read_csv(stats_folder + 'stats_exp_02.csv')

In [3]:
def accumulate_stats(df):
    df_prompt_better_sd = df[(df['term'] != '(Intercept)') & (df['estimate'] > 0) & (df['p_value'] < .05)]
    df_prompt_better_marg = df[(df['term'] != '(Intercept)') & (df['estimate'] > 0) & (df['p_value'] >= .05) & (df['p_value'] < .1)]
    df_prompt_worse_sd = df[(df['term'] != '(Intercept)') & (df['estimate'] < 0) & (df['p_value'] < .05)]
    df_prompt_worse_marg = df[(df['term'] != '(Intercept)') & (df['estimate'] < 0) & (df['p_value'] >= .05) & (df['p_value'] < .1)]
    df_prompt_nsd = df[(df['term'] != '(Intercept)') & (df['estimate'] < 0) & (df['p_value'] >= .1)]
    return (
        df_prompt_better_sd,
        df_prompt_better_marg,
        df_prompt_worse_sd,
        df_prompt_worse_marg,
        df_prompt_nsd
    )

# Experiment 1

In [4]:
(
    df1_prompt_better_sd,
    df1_prompt_better_marg,
    df1_prompt_worse_sd,
    df1_prompt_worse_marg,
    df1_prompt_nsd
) = accumulate_stats(df_1)

In [5]:
print(len(df1_prompt_better_sd))
df1_prompt_better_sd

5

,model,term,estimate,standard_error,z_value,p_value,odds_ratio
12,gemma_4_12B,methodforced_choice_2,1.197834,0.080340,14.909565,2.856066e-50,3.312934
17,gemma_4_26B_A4B,methodforced_choice_2,0.821794,0.071833,11.440277,2.630457e-30,2.274578
21,gemma_4_31B,methodforced_choice_1,1.945329,0.097644,19.922688,2.587214e-88,6.995933
22,gemma_4_31B,methodforced_choice_2,2.638894,0.119855,22.017462,1.959350e-107,13.997714
76,qwen_3.5_27B,methodforced_choice_1,0.509506,0.116933,4.357252,1.317058e-05,1.664469

In [6]:
print(len(df1_prompt_better_marg))
df1_prompt_better_marg

0

Empty DataFrame
Columns: [model, term, estimate, standard_error, z_value, p_value, odds_ratio]
Index: []

In [7]:
print(len(df1_prompt_worse_sd))

56

In [8]:
print(len(df1_prompt_worse_marg))
df1_prompt_worse_marg

0

Empty DataFrame
Columns: [model, term, estimate, standard_error, z_value, p_value, odds_ratio]
Index: []

In [9]:
print(len(df1_prompt_nsd))
df1_prompt_nsd

6

,model,term,estimate,standard_error,z_value,p_value,odds_ratio
11,gemma_4_12B,methodforced_choice_1,-0.048871,0.069198,-0.706250,0.480033,0.952304
19,gemma_4_26B_A4B,methodyes_no_2,-0.064669,0.066092,-0.978466,0.327844,0.937378
24,gemma_4_31B,methodyes_no_2,-0.111671,0.070286,-1.588819,0.112101,0.894338
41,qwen_3_8B,methodforced_choice_1,-0.099212,0.078145,-1.269587,0.204232,0.905551
47,qwen_3_14B,methodforced_choice_2,-0.087130,0.078351,-1.112037,0.266122,0.916558
52,qwen_3_32B,methodforced_choice_2,-0.128996,0.081945,-1.574182,0.115445,0.878977

# Experiment 2

In [10]:
(
    df2_prompt_better_sd,
    df2_prompt_better_marg,
    df2_prompt_worse_sd,
    df2_prompt_worse_marg,
    df2_prompt_nsd
) = accumulate_stats(df_2)

In [11]:
print(len(df2_prompt_better_sd))
df2_prompt_better_sd

12

,model,term,estimate,standard_error,z_value,p_value,odds_ratio
11,gemma_4_12B,methodforced_choice_1,0.359180,0.058746,6.114115,9.709430e-10,1.432155
12,gemma_4_12B,methodforced_choice_2,0.974971,0.062584,15.578574,1.018007e-54,2.651091
16,gemma_4_26B_A4B,methodforced_choice_1,0.295304,0.057566,5.129789,2.900670e-07,1.343534
17,gemma_4_26B_A4B,methodforced_choice_2,0.915655,0.061194,14.963245,1.276470e-50,2.498412
21,gemma_4_31B,methodforced_choice_1,1.425526,0.069789,20.426372,9.748090e-93,4.160045
22,gemma_4_31B,methodforced_choice_2,2.246389,0.083902,26.773942,6.500324e-158,9.453537
41,qwen_3_8B,methodforced_choice_1,0.218507,0.063765,3.426757,6.108356e-04,1.244218
51,qwen_3_32B,methodforced_choice_1,0.227593,0.060199,3.780664,1.564105e-04,1.255574
52,qwen_3_32B,methodforced_choice_2,0.188084,0.060016,3.133883,1.725094e-03,1.206935
76,qwen_3.5_27B,methodforced_choice_1,0.474773,0.068902,6.890525,5.558671e-12,1.607650
77,qwen_3.5_27B,methodforced_choice_2,0.381001,0.068208,5.585866,2.325391e-08,1.463749
81,qwen_3.5_35B_A3B,methodforced_choice_1,0.266444,0.060546,4.400714,1.078953e-05,1.305314

In [12]:
print(len(df2_prompt_better_marg))
df2_prompt_better_marg

1

,model,term,estimate,standard_error,z_value,p_value,odds_ratio
36,qwen_3_4B,methodforced_choice_1,0.110054,0.061127,1.800412,0.071796,1.116338

In [13]:
print(len(df2_prompt_worse_sd))

46

In [14]:
print(len(df2_prompt_worse_marg))
df2_prompt_worse_marg

1

,model,term,estimate,standard_error,z_value,p_value,odds_ratio
6,gemma_4_E4B,methodforced_choice_1,-0.11059,0.05787,-1.910988,0.056006,0.895306

In [15]:
print(len(df2_prompt_nsd))
df2_prompt_nsd

5

,model,term,estimate,standard_error,z_value,p_value,odds_ratio
2,gemma_4_E2B,methodforced_choice_2,-0.062107,0.058251,-1.066193,0.286336,0.939782
7,gemma_4_E4B,methodforced_choice_2,-0.023976,0.058055,-0.412990,0.679614,0.976309
42,qwen_3_8B,methodforced_choice_2,-0.097957,0.062713,-1.561990,0.118290,0.906688
47,qwen_3_14B,methodforced_choice_2,-0.094225,0.062180,-1.515377,0.129677,0.910078
71,qwen_3.5_9B,methodforced_choice_1,-0.085227,0.060413,-1.410726,0.158325,0.918304